### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by dharma282** [toutpuissantged/clickbot-monster#1]
Earn money using telegram bot.                                                                                                Options:
                                                                                0 Dogecoin_click_bot                                                   1 Litecoin_click_bot
         2 BCH_clickbot                                                         3 Zcash_click_bot                                                      4 Bitcoinclick_bot
                                                                               Which bot do you want to run? (Number only):3                  Zcash_click_bot selected.
                                                                                       DogeClick Bot Channel Actions Menu.                    
 Options:                                                                                                                                              0 Visit
         1 Message                                                              2 Join                                                        
        What bot's action do you want to perform? (Number only):0      Visit performed                                                        Please enter the code you received: 28327
Traceback (most recent call last):
  File "/storage/emulated/0/movies/clickbot-monster/main.py", line 266, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/storage/emulated/0/movies/clickbot-monster/main.py", line 77, in main
    await client.start(phone_number)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 207, in _start
    me = await self.sign_in(phone, code=value)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 78, in _call
    self.session.process_entities(result)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sessions/sqlite.py", line 281, in process_entities
    c.executemany(
sqlite3.OperationalError: table entities has 6 columns but 5 values were supplied

**Comment by dharma282** [comment]
I ran it with termux

**Comment by toutpuissantged** [comment]
the script worked on termux until recently when updating telegram but i am reviewing the code for a v2. Thank you for your comment
